-- Persist per-payment fees and totals
ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS fee_transfer_inr DOUBLE PRECISION NOT NULL DEFAULT 99.0,
    ADD COLUMN IF NOT EXISTS fee_platform_inr DOUBLE PRECISION NOT NULL DEFAULT 25.0,
    ADD COLUMN IF NOT EXISTS fee_src_total DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS total_inr DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS total_src DOUBLE PRECISION NOT NULL DEFAULT 0.0;

